const fs = require("fs");
const path = require("path");

const root = __dirname;
const photoDir = path.join(root, "assets", "img", "photo");
const textPath = path.join(root, "assets", "text", "夢境紀.txt");
const outputPath = path.join(root, "content.generated.js");
const watchMode = process.argv.includes("--watch");
const checkMode = process.argv.includes("--check");
const supportedImagePattern = /\.(gif|jpe?g|png|webp)$/i;

function listPhotos() {
  if (!fs.existsSync(photoDir)) return [];

  return fs.readdirSync(photoDir)
    .filter((name) => !name.startsWith("."))
    .filter((name) => supportedImagePattern.test(name))
    .sort((a, b) => a.localeCompare(b, "en"))
    .map((name) => `photo/${name}`);
}

function buildContent() {
  const dreamText = fs.existsSync(textPath) ? fs.readFileSync(textPath, "utf8") : "";
  const photos = listPhotos();
  const output = [
    "// Generated by sync-content.js. Do not edit this file directly.",
    `window.AK100_DREAM_TEXT = ${JSON.stringify(dreamText)};`,
    `window.AK100_PHOTOS = ${JSON.stringify(photos, null, 2)};`,
    ""
  ].join("\n");

  return { dreamText, photos, output };
}

function syncContent() {
  const { dreamText, photos, output } = buildContent();

  fs.writeFileSync(outputPath, output);
  console.log(`content.generated.js updated: ${photos.length} photos, ${dreamText.length} text chars`);
}

function checkContent() {
  const { output } = buildContent();
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";

  if (current !== output) {
    console.error("content.generated.js is out of date. Run: node sync-content.js");
    process.exitCode = 1;
    return;
  }

  console.log("content.generated.js is current");
}

if (checkMode) {
  checkContent();
} else {
  syncContent();
}

if (watchMode) {
  let timer;
  const scheduleSync = () => {
    clearTimeout(timer);
    timer = setTimeout(syncContent, 120);
  };

  if (fs.existsSync(photoDir)) fs.watch(photoDir, scheduleSync);
  if (fs.existsSync(textPath)) fs.watch(textPath, scheduleSync);
  console.log("watching assets/img/photo/ and assets/text/夢境紀.txt");
}
